### ISSUE TITLE
Replace directories containing reserved Windows characters

### ISSUE THREAD

**Issue by ZachTRice** [nasa/cumulus-dashboard#570]
Cloning this repository on a Windows machine currently breaks due to the use of reserved (`:`) characters in this directory path:
https://github.com/nasa/cumulus-dashboard/tree/develop/test/fake-api/fixtures/executions/status

Error:
```
fatal: cannot create directory at 'test/fake-api/fixtures/executions/status/arn:aws:states:us-east-1:596205514787:execution:TestSourceIntegrationDiscoverAndQueuePdrsStateMachine-T4MDdDs9ADnK:c3ce6b76-a5f5-47d2-80a5-8b5c56300da8': Invalid argument
warning: Clone succeeded, but checkout failed.
```
This type of error prevents those files from downloading and the end-user from switching branches, resetting the head, etc.

**Comment by markdboyd** [comment]
@ZachTRice Can you try cloning the `hotfix-570-windows-directory-names` branch and see if that works in the Windows shell?

**Comment by ZachTRice** [comment]
👍 This is working, thanks for the update

**Comment by markdboyd** [comment]
@ZachTRice This fix has been merged to `master`, so everything should work on a fresh clone of the repo or if you switch to working off of `master`. In general, we recommend working off of `master`.
